# Generated by Django 6.1 on 2026-08-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_students', 'Can view students'), ('can_manage_students', 'Can manage students')]},
        ),
    ]
