# Generated by Django 6.1 on 2026-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('course', models.CharField(choices=[('ECE', 'Electronics and Communication'), ('CSE', 'Computer Science'), ('ISE', 'Information Science')], max_length=3)),
                ('joined_date', models.DateField()),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
